---
title: "Dia 13"
author: "Bioing. Agustin Solano"
date: "24/5/2020"
output: pdf_document
---


Levanto librerias necesarias
```{r}
if("dplyr" %in% (.packages())){
          detach("package:dplyr", unload=TRUE) 
          detach("package:plyr", unload=TRUE) 
} 
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(png)
library(grid)
library(forcats)
library(zoo)
```

```{r }
datos = read.csv('GlobalTemperatures.csv',na.strings = "")
str(datos)
summary(datos)
```

```{r}
datosAvrg = datos %>%
  select(dt,LandAverageTemperature,LandAverageTemperatureUncertainty ) %>%
  mutate(dt=as.Date(dt,format("%Y-%m-%d"))) %>%
  mutate(LandAverageTemperature_MA = rollmean(LandAverageTemperature,12,fill = list(NA, NULL, NA)))
datosAvrg

datosMinMax = datos %>%
  select(dt,LandMaxTemperature,LandMinTemperature) %>%
  mutate(dt=as.Date(dt,format("%Y-%m-%d"))) %>%
  mutate(LandMinTemperature_MA = rollmean(LandMinTemperature,12,fill = list(NA, NULL, NA)),
         LandMaxTemperature_MA = rollmean(LandMaxTemperature,12,fill = list(NA, NULL, NA))) %>%
  filter(dt>as.Date("1850-06-01",format("%Y-%m-%d"))) %>%
  pivot_longer(cols = LandMaxTemperature:LandMaxTemperature_MA,names_to = "variable", values_to = "temp")
datosMinMax
```

```{r}
g1 = ggplot() +
  geom_line(data=datosAvrg,aes(x=dt,y=LandAverageTemperature),alpha=.1) +
  # geom_ribbon(data=datosAvrg,aes(x=dt,ymin=LandAverageTemperature-LandAverageTemperatureUncertainty,
  #                 ymax=LandAverageTemperature+LandAverageTemperatureUncertainty),fill="coral1",alpha=0.3) +
  geom_line(data=datosAvrg,aes(x=dt,y=LandAverageTemperature_MA),color="deeppink4",size=1.3) +
  labs(title = "Temperatura promedio de la Tierra (° Celsius)",
              subtitle = "Promedio y ventana movil por año",
              caption = "@Aguchosolano") +
  ylab("Temperatura [°C]") + xlab(NULL) +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "#FEF2F0"),
        axis.text.x = element_text(size=12),axis.text.y = element_text(size=12),
        axis.title.y = element_text(size=14,face="bold"))
g1

g2 = ggplot() +
  # geom_line(data=datosMinMax%>%filter((variable=="LandMaxTemperature")|(variable=="LandMinTemperature")),
  #           aes(x=dt,y=temp),size=0.5,alpha=0.2) +
  geom_line(data=datosMinMax%>%filter((variable!="LandMaxTemperature")&(variable!="LandMinTemperature"))
            ,aes(x=dt,y=temp,color=variable),alpha=.7) +
  geom_smooth(data=datosMinMax%>%filter((variable!="LandMaxTemperature")&(variable!="LandMinTemperature"))
            ,aes(x=dt,y=temp,group=variable),method = lm, se = FALSE,color="gray24") +
  scale_color_manual(values = c("red3","royalblue4"), labels = c("Temp. Max","Temp. Min"),name=NULL) +
  labs(title = "Temperatura Max y Minimo de la Tierra (° Celsius)",
              subtitle = "Ventana movil por año y aproximación lineal",
              caption = "@Aguchosolano") +
  ylab("Temperatura [°C]") + xlab(NULL) +
  guides(fill=NULL)+
  ylim(0,18) +
  theme_classic() +
  theme(axis.text.x = element_text(size=12),axis.text.y = element_text(size=12),
        axis.title.y = element_text(size=14,face="bold"),
        aspect.ratio = 1/2.5)
g2

# g1 = ggplot(data=datosProcAreasGrandes, aes(x=Area.Geografica, y=value,color=TIC)) +
#   geom_point(aes(shape=TIC,fill=TIC),color="tan", position = position_dodge(.5),
#              size=7,stroke=2) + 
#   geom_linerange(aes(ymin=0, ymax=value), position = position_dodge(.5),show.legend = FALSE,
#                  size=1.5) +
#   scale_shape_manual(values = c(24,21),labels=c("Tiene computadora?","Accede a Internet?"),name=NULL) +
#   scale_fill_brewer(palette = "Set1",labels=c("Tiene computadora?","Accede a Internet?"),name=NULL) +
#   guides(color=NULL) +
#   ylim(0,100) +
#   scale_x_discrete(labels=c("Ciudad Autonoma de Buenos Aires (2)" = "CABA",
#                             "Partidos del Gran Buenos Aires ( 2)" = "PBA"), name=NULL) +
#   ylab("% Respuestas Afirmativas") +
#   theme_minimal() +
#   theme(panel.grid.major.x = element_blank(),legend.position = "top",
#         panel.grid = element_line(color = "black"), 
#         axis.text.x = element_text(size=13,face="bold",angle=15),axis.text.y = element_text(size=14),
#         axis.title.y = element_text(size=17,face="bold"),
#         plot.background = element_rect(fill = "#DBE485"),
#         legend.text = element_text(size=12))
#   g1
#   
#   g2 = ggplot(data=datosProcAreasParticulares, aes(x=Area.Geografica, y=value,color=TIC)) +
#   geom_point(aes(shape=TIC,fill=TIC),color="black", position = position_dodge(.5),
#              size=3,stroke=1.5) + 
#   geom_linerange(aes(ymin=0, ymax=value), position = position_dodge(.5),show.legend = FALSE,
#                  size=1) +
#   scale_shape_manual(values = c(22,23),labels=c("Tiene computadora?","Accede a Internet?"),name=NULL) +
#   scale_fill_manual(values=c("royalblue3","maroon3"),labels=c("Tiene computadora?","Accede a Internet?"),name=NULL) +
#   scale_color_manual(values=c("royalblue3","maroon3"),name=NULL) +
#   guides(color=NULL) +
#   ylim(0,100) +
#   scale_x_discrete(labels=c("Ciudad Autónoma de Buenos Aires (2)" = "CABA",
#                             "Partidos del Gran Buenos Aires ( 2)" = "PBA"), name=NULL) +
#   ylab("% Respuestas Afirmativas") +
#   theme_minimal() +
#   theme(panel.grid.major.x = element_blank(),legend.position = "top",
#         panel.grid = element_line(color = "black"), 
#         axis.text.x = element_text(size=12,face="bold",angle=90,vjust = 1.2),axis.text.y = element_text(size=14),
#         axis.title.y = element_text(size=17,face="bold"),
#         plot.background = element_rect(fill = "wheat"),
#         legend.text = element_text(size=12))
#   g2
  
```

```{r}
ggsave("Dia13_TempAvrg.png",plot=g1,units = 'mm',dpi=300)
ggsave("Dia13_TempMaxMin.png",plot=g2,units = 'mm',dpi=300)
```



