---
title: "Mundiales de Futbol - Datos de Miercoles"
author: "Agustin Solano"
date: "13 de abril de 2019"
output: pdf_document
---

Librerias a utilizar
```{r}
library(readr)
library(stringr)
library(ggplot2)
```


Levanto los datos provistos
```{r}
# install.packages(readr)

partidos_fifa_copa_mundial_procesado <- readr::read_delim("partidos.txt",delim = "\t")

partidos_fifa_copa_mundial_crudo <- readr::read_delim("partidos_crudo.txt",delim = "\t")
```

Pregunta 1: quien es el equipo que mas partidos gano en mundiales y quien es el que tiene mayor proporciones de partidos ganados?
```{r}
#lista total de equipos que jugaron en algun mundial
paises = c(partidos_fifa_copa_mundial_procesado$equipo_1,partidos_fifa_copa_mundial_procesado$equipo_2)

listaPaises = unique(paises)
listaPaises = listaPaises[listaPaises!="Republica de Irlanda"&listaPaises!="Irlanda del Norte"&
                  listaPaises!="Alemania occidental"&listaPaises!="Alemania del Este"&
                  listaPaises!="Serbia y Montenegro"]

cantPartidosPais = data.frame()
for (i in 1:length(listaPaises))
{
  cant = sum(str_count(paises,listaPaises[i]))
  aux=data.frame(pais=listaPaises[i],cant=cant)
  cantPartidosPais = rbind(cantPartidosPais,aux)
  
}


ganaEquipo1 = partidos_fifa_copa_mundial_procesado$equipo_1_final>partidos_fifa_copa_mundial_procesado$equipo_2_final
ganaEquipo2 = partidos_fifa_copa_mundial_procesado$equipo_2_final>partidos_fifa_copa_mundial_procesado$equipo_1_final

#equipos que ganaron algun partido
equiposGanadores = c(partidos_fifa_copa_mundial_procesado$equipo_1[ganaEquipo1],partidos_fifa_copa_mundial_procesado$equipo_2[ganaEquipo2])

listaPaisesGanadores=unique(equiposGanadores)
listaPaisesGanadores = listaPaisesGanadores[listaPaisesGanadores!="Republica de Irlanda"&
                                              listaPaisesGanadores!="Irlanda del Norte"&
                  listaPaisesGanadores!="Alemania occidental"&listaPaisesGanadores!="Alemania del Este"&
                  listaPaisesGanadores!="Serbia y Montenegro"]

ganadores=data.frame()
for (i in 1:length(listaPaisesGanadores))
{
  
  cant = sum(str_count(equiposGanadores,listaPaisesGanadores[i]))
  aux=data.frame(pais=listaPaisesGanadores[i],cantGanados=cant,
                 cantJugados=cantPartidosPais$cant[str_detect(cantPartidosPais$pais,listaPaisesGanadores[i])])
  ganadores=rbind(ganadores,aux)

}
ganadores$porcGanados = ganadores$cantGanados/ganadores$cantJugados*100

```

Voy a agregar un factor para indicar los paises que ganaron al menos un mundial. Saco los datos de:
https://es.digitaltrends.com/deportes/paises-campeones-copa-mundial-fifa/
```{r}
ganadores$ganoMundial = ganadores$pais=="Brasil"|ganadores$pais=="Italia"|ganadores$pais=="Alemania"|
                        ganadores$pais=="Uruguay"|ganadores$pais=="Argentina"|ganadores$pais=="Inglaterra"|
                        ganadores$pais=="Francia"|ganadores$pais=="España"
```



Grafico
```{r}
#Voy a ordenar los datos de mayor a menor cantidad de partidos ganados
ganadores$pais = factor(ganadores$pais,levels=ganadores$pais[order(ganadores$cantGanados,decreasing=F)]) 

ggplot(data=ganadores,aes(x=pais,y=cantGanados,fill=ganoMundial)) +
  geom_col() +
  #scale_fill_brewer(palette="Pastel2")+
  scale_fill_manual(values=c("tomato","cornflowerblue"),name = "Ganó algún mundial?", labels = c("No", "Si"))+
  ggtitle("Cantidad de partidos ganados por pais")+
  theme_light() +
  theme(axis.text.y=element_text(size=5))+
  coord_flip()
ggsave("equiposMasPartidosGanados.png",plot = last_plot())

#Voy a ordenar los datos de mayor a menor porcentaje de partidos ganados
ganadores$pais = factor(ganadores$pais,levels=ganadores$pais[order(ganadores$porcGanados,decreasing=F)]) 

ggplot(data=ganadores,aes(x=pais,y=porcGanados,fill=ganoMundial)) +
  geom_col() +
  scale_fill_manual(values=c("tomato","cornflowerblue"),name = "Ganó algún mundial?", labels = c("No", "Si"))+
  ggtitle("Porcentaje de partidos ganados por pais")+
  theme_light() +
  theme(axis.text.y=element_text(size=5))+
  ylim(0,100) +
  coord_flip()
ggsave("equiposMasGanadores.png",plot = last_plot())

ggplot(data=ganadores[order(ganadores$porcGanados,decreasing=T)[1:20],],aes(x=pais,y=porcGanados,fill=ganoMundial)) +
  geom_col() +
  scale_fill_manual(values=c("tomato","cornflowerblue"),name = "Ganó algún mundial?", labels = c("No", "Si"))+
  ggtitle("Porcentaje de partidos ganados por pais (20 mas ganadores)")+
  theme_light() +
  ylim(0,100) +
  coord_flip()
ggsave("20equiposMasGanadores.png",plot = last_plot())
```

